---
name: Rebuild

# scheduled GH-actions will run on the default branch only, master
on:
  schedule:
    - cron: "30 3 * * 2"

env:
  HAS_SECRETS: ${{ secrets.HAS_SECRETS }}

jobs:
  rebuild:
    runs-on: ubuntu-20.04
    name: Rebuild
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        branch:
          - master

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{matrix.branch}}

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
          patterns: docker
        if: github.repository == 'camptocamp/docker-geoserver'

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --requirement=ci/requirements.txt

      - name: Checks
        run: c2cciutils-checks

      - run: make pull
      - run: make build

      - name: Publish
        run: c2cciutils-publish --type=rebuild --branch=${{matrix.branch}}
        if: env.HAS_SECRETS == 'HAS_SECRETS'
